version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'friday'
    commit-message:
      prefix: 'yarn'
      include: 'scope'
    target-branch: 'qa'
    labels:
      - 'yarn'
      - 'dependencies'
