/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsConfig = {
  aws_project_region: process.env.NEXT_PUBLIC_COGNITO_REGION,
  // aws_cognito_region: process.env.NEXT_PUBLIC_COGNITO_REGION,
  // aws_user_pools_id: process.env.NEXT_PUBLIC_COGNITO_USERPOOL,
  // aws_user_pools_web_client_id: process.env.NEXT_PUBLIC_COGNITO_CLIENT_ID,
  Analytics: {
    disabled: true,
  },
  Auth: {
    region: process.env.NEXT_PUBLIC_COGNITO_REGION,
    userPoolId: process.env.NEXT_PUBLIC_COGNITO_USERPOOL,
    userPoolWebClientId: process.env.NEXT_PUBLIC_COGNITO_CLIENT_ID,
    mandatorySignIn: false,
    cookieStorage: {
      domain: process.env.NEXT_PUBLIC_AMPLIFY_COOKIE_DOMAIN,
      path: "/",
      expires: 10,
      sameSite: "strict",
      secure: true,
    },

    oauth: {
      domain: process.env.NEXT_PUBLIC_COGNITO_DOMAIN,
      scope: [
        "aws.cognito.signin.user.admin",
        "email",
        "openid",
        "phone",
        "profile",
      ],
      redirectSignIn: process.env.NEXT_PUBLIC_COGNITO_REDIRECT_SIGNIN,
      redirectSignOut: process.env.NEXT_PUBLIC_COGNITO_REDIRECT_SIGNOUT,
      responseType: "code",
    },
    federationTarget: "COGNITO_USER_POOLS",
  },
  federationTarget: "COGNITO_USER_POOLS",
};

export default awsConfig;
