name: Deploy to Prod
on: workflow_dispatch
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_email: "sandeepkhoj@gmail.com"
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "aolf-web"
